import { Member } from "./member";

export const MEMBERS:Member[] = 
[
  {
    rank: "1",
    member: "Lepilou",
    points: "1081841063",
    eraID: "21",
    eraName: "Ère spatiale - Lune de Jupiter",
    activity_warnings: "0",
    messages: "193",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "313956",
    guildmember: "1",
  },
  {
    rank: "2",
    member: "Fred le Pillard",
    points: "856058706",
    eraID: "21",
    eraName: "Ère spatiale - Lune de Jupiter",
    activity_warnings: "0",
    messages: "272",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "219035",
    guildmember: "1",
  },
  {
    rank: "3",
    member: "JLO1965",
    points: "537514746",
    eraID: "20",
    eraName: "Ère spatiale - Vénus",
    activity_warnings: "0",
    messages: "28",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "146332",
    guildmember: "1",
  },
  {
    rank: "4",
    member: "Christophe1979",
    points: "324743970",
    eraID: "17",
    eraName: "Futur virtuel",
    activity_warnings: "0",
    messages: "460",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "179883",
    guildmember: "1",
  },
  {
    rank: "5",
    member: "jekell",
    points: "291762029",
    eraID: "20",
    eraName: "Ère spatiale - Vénus",
    activity_warnings: "0",
    messages: "108",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "82875",
    guildmember: "1",
  },
  {
    rank: "6",
    member: "CesarDelgado",
    points: "279787277",
    eraID: "21",
    eraName: "Ère spatiale - Lune de Jupiter",
    activity_warnings: "0",
    messages: "34",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "46441",
    guildmember: "1",
  },
  {
    rank: "7",
    member: "bgk972",
    points: "223103805",
    eraID: "21",
    eraName: "Ère spatiale - Lune de Jupiter",
    activity_warnings: "1",
    messages: "46",
    gex_participation: "2",
    gbg_participation: "1",
    won_battles: "28828",
    guildmember: "1",
  },
  {
    rank: "8",
    member: "lodell",
    points: "194937039",
    eraID: "21",
    eraName: "Ère spatiale - Lune de Jupiter",
    activity_warnings: "0",
    messages: "64",
    gex_participation: "2",
    gbg_participation: "1",
    won_battles: "32066",
    guildmember: "1",
  },
  {
    rank: "9",
    member: "mistinguette32",
    points: "187884277",
    eraID: "20",
    eraName: "Ère spatiale - Vénus",
    activity_warnings: "2",
    messages: "8",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "55347",
    guildmember: "1",
  },
  {
    rank: "10",
    member: "Casticus 368 le Chasseur",
    points: "155403053",
    eraID: "21",
    eraName: "Ère spatiale - Lune de Jupiter",
    activity_warnings: "0",
    messages: "5",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "25261",
    guildmember: "1",
  },
  {
    rank: "11",
    member: "Narscors",
    points: "139053844",
    eraID: "17",
    eraName: "Futur virtuel",
    activity_warnings: "0",
    messages: "89",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "96775",
    guildmember: "1",
  },
  {
    rank: "12",
    member: "chuck norrris",
    points: "128610386",
    eraID: "17",
    eraName: "Futur virtuel",
    activity_warnings: "0",
    messages: "386",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "96782",
    guildmember: "1",
  },
  {
    rank: "13",
    member: "Séléné 764 la Cruelle",
    points: "126055166",
    eraID: "17",
    eraName: "Futur virtuel",
    activity_warnings: "0",
    messages: "50",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "27248",
    guildmember: "1",
  },
  {
    rank: "14",
    member: "all taieb",
    points: "113164098",
    eraID: "19",
    eraName: "Ère spatiale - Ceinture d'astéroïdes",
    activity_warnings: "4",
    messages: "8",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "26772",
    guildmember: "1",
  },
  {
    rank: "15",
    member: "denethil",
    points: "102758731",
    eraID: "16",
    eraName: "Futur océanique",
    activity_warnings: "0",
    messages: "63",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "35654",
    guildmember: "1",
  },
  {
    rank: "16",
    member: "IorekB",
    points: "97993725",
    eraID: "19",
    eraName: "Ère spatiale - Ceinture d'astéroïdes",
    activity_warnings: "0",
    messages: "0",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "22316",
    guildmember: "1",
  },
  {
    rank: "17",
    member: "jaydeeya",
    points: "97840128",
    eraID: "18",
    eraName: "Ère spatiale - Mars",
    activity_warnings: "0",
    messages: "7",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "32909",
    guildmember: "1",
  },
  {
    rank: "18",
    member: "awax6",
    points: "87505436",
    eraID: "11",
    eraName: "Ère Postmoderne",
    activity_warnings: "0",
    messages: "66",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "139191",
    guildmember: "1",
  },
  {
    rank: "19",
    member: "Honorius 666 le Chasseur",
    points: "80062328",
    eraID: "15",
    eraName: "Futur arctique",
    activity_warnings: "0",
    messages: "166",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "37897",
    guildmember: "1",
  },
  {
    rank: "20",
    member: "bullitt666",
    points: "79166969",
    eraID: "19",
    eraName: "Ère spatiale - Ceinture d'astéroïdes",
    activity_warnings: "0",
    messages: "6",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "19010",
    guildmember: "1",
  },
  {
    rank: "21",
    member: "Rumsteck le musclay",
    points: "75409863",
    eraID: "16",
    eraName: "Futur océanique",
    activity_warnings: "1",
    messages: "12",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "25911",
    guildmember: "1",
  },
  {
    rank: "22",
    member: "Samneveu",
    points: "72787272",
    eraID: "18",
    eraName: "Ère spatiale - Mars",
    activity_warnings: "0",
    messages: "7",
    gex_participation: "2",
    gbg_participation: "1",
    won_battles: "5872",
    guildmember: "1",
  },
  {
    rank: "23",
    member: "Karel Alchimiste",
    points: "69942322",
    eraID: "13",
    eraName: "Demain",
    activity_warnings: "0",
    messages: "61",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "60601",
    guildmember: "1",
  },
  {
    rank: "24",
    member: "agguy",
    points: "66718670",
    eraID: "14",
    eraName: "Ère du Futur",
    activity_warnings: "0",
    messages: "40",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "30913",
    guildmember: "1",
  },
  {
    rank: "25",
    member: "Clément le Destructeur",
    points: "66358593",
    eraID: "14",
    eraName: "Ère du Futur",
    activity_warnings: "1",
    messages: "46",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "33539",
    guildmember: "1",
  },
  {
    rank: "25",
    member: "Eleanor 73",
    points: "64147907",
    eraID: "17",
    eraName: "Futur virtuel",
    activity_warnings: "0",
    messages: "20",
    gex_participation: "1",
    gbg_participation: "1",
    won_battles: "19217",
    guildmember: "0",
  },
  {
    rank: "26",
    member: "MagicHannibal",
    points: "61375132",
    eraID: "14",
    eraName: "Ère du Futur",
    activity_warnings: "0",
    messages: "137",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "44957",
    guildmember: "1",
  },
  {
    rank: "27",
    member: "Scorpion 13",
    points: "59928792",
    eraID: "14",
    eraName: "Ère du Futur",
    activity_warnings: "0",
    messages: "49",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "49346",
    guildmember: "1",
  },
  {
    rank: "28",
    member: "looping620",
    points: "59690769",
    eraID: "8",
    eraName: "Âge Industriel",
    activity_warnings: "0",
    messages: "138",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "125914",
    guildmember: "1",
  },
  {
    rank: "29",
    member: "SirBoubou",
    points: "58746324",
    eraID: "15",
    eraName: "Futur arctique",
    activity_warnings: "0",
    messages: "11",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "26295",
    guildmember: "1",
  },
  {
    rank: "29",
    member: "djenépi",
    points: "57776190",
    eraID: "11",
    eraName: "Ère Postmoderne",
    activity_warnings: "0",
    messages: "40",
    gex_participation: "2",
    gbg_participation: "1",
    won_battles: "31468",
    guildmember: "0",
  },
  {
    rank: "30",
    member: "oliv79",
    points: "56961870",
    eraID: "13",
    eraName: "Demain",
    activity_warnings: "0",
    messages: "34",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "79766",
    guildmember: "1",
  },
  {
    rank: "31",
    member: "Cirïus",
    points: "51460618",
    eraID: "13",
    eraName: "Demain",
    activity_warnings: "9",
    messages: "1",
    gex_participation: "2",
    gbg_participation: "0",
    won_battles: "25754",
    guildmember: "1",
  },
  {
    rank: "32",
    member: "Patrocle69",
    points: "50624204",
    eraID: "9",
    eraName: "Ère Progressiste",
    activity_warnings: "0",
    messages: "90",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "50719",
    guildmember: "1",
  },
  {
    rank: "33",
    member: "Jacquouille4",
    points: "47982677",
    eraID: "18",
    eraName: "Ère spatiale - Mars",
    activity_warnings: "0",
    messages: "7",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "5949",
    guildmember: "1",
  },
  {
    rank: "34",
    member: "fanch83",
    points: "46392374",
    eraID: "16",
    eraName: "Futur océanique",
    activity_warnings: "0",
    messages: "25",
    gex_participation: "2",
    gbg_participation: "0",
    won_battles: "1890",
    guildmember: "1",
  },
  {
    rank: "35",
    member: "Loup115",
    points: "40655912",
    eraID: "14",
    eraName: "Ère du Futur",
    activity_warnings: "0",
    messages: "92",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "23375",
    guildmember: "1",
  },
  {
    rank: "36",
    member: "JamesKalan",
    points: "39301370",
    eraID: "10",
    eraName: "Ère Moderne",
    activity_warnings: "0",
    messages: "26",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "45000",
    guildmember: "1",
  },
  {
    rank: "37",
    member: "Joe94370",
    points: "39073831",
    eraID: "9",
    eraName: "Ère Progressiste",
    activity_warnings: "0",
    messages: "39",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "26544",
    guildmember: "1",
  },
  {
    rank: "38",
    member: "pjt53",
    points: "36127591",
    eraID: "11",
    eraName: "Ère Postmoderne",
    activity_warnings: "0",
    messages: "81",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "26166",
    guildmember: "1",
  },
  {
    rank: "39",
    member: "Ysiaah",
    points: "35824511",
    eraID: "10",
    eraName: "Ère Moderne",
    activity_warnings: "0",
    messages: "59",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "64974",
    guildmember: "1",
  },
  {
    rank: "40",
    member: "Keral",
    points: "34370588",
    eraID: "10",
    eraName: "Ère Moderne",
    activity_warnings: "0",
    messages: "352",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "59468",
    guildmember: "1",
  },
  {
    rank: "41",
    member: "miss kinder",
    points: "28166346",
    eraID: "9",
    eraName: "Ère Progressiste",
    activity_warnings: "1",
    messages: "80",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "41680",
    guildmember: "1",
  },
  {
    rank: "42",
    member: "Cyr.81",
    points: "27922503",
    eraID: "9",
    eraName: "Ère Progressiste",
    activity_warnings: "0",
    messages: "91",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "55990",
    guildmember: "1",
  },
  {
    rank: "43",
    member: "Astellan",
    points: "23325590",
    eraID: "13",
    eraName: "Demain",
    activity_warnings: "0",
    messages: "88",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "14703",
    guildmember: "1",
  },
  {
    rank: "44",
    member: "Nono 1717 la Terrible",
    points: "21815866",
    eraID: "12",
    eraName: "Ère Contemporaine",
    activity_warnings: "0",
    messages: "19",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "17046",
    guildmember: "1",
  },
  {
    rank: "45",
    member: "Belli 1er le croquant",
    points: "20627837",
    eraID: "11",
    eraName: "Ère Postmoderne",
    activity_warnings: "0",
    messages: "97",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "9871",
    guildmember: "1",
  },
  {
    rank: "46",
    member: "Waidmann",
    points: "20309593",
    eraID: "8",
    eraName: "Âge Industriel",
    activity_warnings: "0",
    messages: "38",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "40820",
    guildmember: "1",
  },
  {
    rank: "47",
    member: "jamy038",
    points: "16536076",
    eraID: "9",
    eraName: "Ère Progressiste",
    activity_warnings: "0",
    messages: "36",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "27253",
    guildmember: "1",
  },
  {
    rank: "48",
    member: "Artémisia absinthium",
    points: "16122580",
    eraID: "12",
    eraName: "Ère Contemporaine",
    activity_warnings: "0",
    messages: "17",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "6193",
    guildmember: "1",
  },
  {
    rank: "49",
    member: "Papilou des îles",
    points: "14572853",
    eraID: "10",
    eraName: "Ère Moderne",
    activity_warnings: "0",
    messages: "45",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "18721",
    guildmember: "1",
  },
  {
    rank: "50",
    member: "Jyjy 1er",
    points: "12711037",
    eraID: "8",
    eraName: "Âge Industriel",
    activity_warnings: "1",
    messages: "24",
    gex_participation: "1",
    gbg_participation: "2",
    won_battles: "8213",
    guildmember: "1",
  },
  {
    rank: "51",
    member: "ASR3",
    points: "9571341",
    eraID: "9",
    eraName: "Ère Progressiste",
    activity_warnings: "0",
    messages: "112",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "8356",
    guildmember: "1",
  },
  {
    rank: "52",
    member: "tootou3815",
    points: "8391735",
    eraID: "8",
    eraName: "Âge Industriel",
    activity_warnings: "0",
    messages: "27",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "9253",
    guildmember: "1",
  },
  {
    rank: "53",
    member: "lamiche2",
    points: "8206406",
    eraID: "9",
    eraName: "Ère Progressiste",
    activity_warnings: "6",
    messages: "11",
    gex_participation: "2",
    gbg_participation: "2",
    won_battles: "10689",
    guildmember: "1",
  },
];
